### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="c1a5a-101">Configuración, implementación y ejecución en Azure</span><span class="sxs-lookup"><span data-stu-id="c1a5a-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="c1a5a-102">Configuración, implementación y ejecución en Azure</span><span class="sxs-lookup"><span data-stu-id="c1a5a-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="c1a5a-103">Configuración, implementación y ejecución en Azure</span><span class="sxs-lookup"><span data-stu-id="c1a5a-103">Configure, deploy, and run in Azure</span></span>
  ms.openlocfilehash: 2877e343b38fce7016c15621f390db6343838e7d
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40445777"
durationInMinutes: 10
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
