### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: Configuración, implementación y ejecución en Azure
metadata:
  title: Configuración, implementación y ejecución en Azure
  description: Configuración, implementación y ejecución en Azure
  ms.openlocfilehash: 2877e343b38fce7016c15621f390db6343838e7d
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40445777"
durationInMinutes: 10
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
