### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: <span data-ttu-id="41ec4-101">Configuración e inicialización de la biblioteca cliente</span><span class="sxs-lookup"><span data-stu-id="41ec4-101">Configure and initialize the client library</span></span>
metadata:
  title: <span data-ttu-id="41ec4-102">Configuración e inicialización de la biblioteca cliente</span><span class="sxs-lookup"><span data-stu-id="41ec4-102">Configure and initialize the client library</span></span>
  description: <span data-ttu-id="41ec4-103">Configuración e inicialización de la biblioteca cliente</span><span class="sxs-lookup"><span data-stu-id="41ec4-103">Configure and initialize the client library</span></span>
  ms.openlocfilehash: c7cc43321a9dc94f71e7689a47ca31e8fe7c774c
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40443819"
durationInMinutes: 10
interactive: bash-editor
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
